baseURL = "https://manualbashing.github.io/"
languageCode = "en-us"
title = "ManualBashing"
theme = "yinyang"
DefaultContentLanguage = "en"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    anchorLineNos = false
    codeFences = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noHl = false
    style = 'emacs'
    tabWidth = 4



[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1

[params]
mainSections = ["posts"]
headTitle = "ManualBashing"
disqus = "manualbashing" # disqus account name
#extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxx"></script>'
twitterCards = true

[[params.socials]]
name = "About"
link = "/about"
[[params.socials]]
name = "Github"
link = "https://github.com/manualbashing"
[[params.socials]]
name = "Twitter"
link = "https:/twitter.com/manualbashing"
[[params.socials]]
name = "RSS"
link = "/index.xml"

# extraCSSFiles = ["css/foo.css", "css/bar.css"]
extraCSSFiles = []

